In [26]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd
plt.style.use("fivethirtyeight")

In [3]:
!pip install joblib



[notice] A new release of pip is available: 23.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [92]:
class perceptorn:
    def __init__(self,eta:float=None, epochs:int=None):
        self.weight=np.random.randn(3)*1e-4
        self.eta=eta
        self.epochs=epochs
        
    def weightUpdate(self, X_biased, weight):
        return np.dot(X_biased, weight)
    
    def activationFuction(self, z):
        return np.where(z>0,1,0)
    
    def fit(self, X, Y):
        self.x=X
        self.y=Y
        
        X_biased=np.c_[self.x,-np.ones((len(self.x),1))]#concatnation of x with bias
        
        for i in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {i + 1}")
            print("--"*10)
            
            z= self.weightUpdate(X_biased, self.weight)
            yUpdate=self.activationFuction(z)
            print(f"predicted value after forward pass: \n{yUpdate}")
            #print('Updated y is ', yUpdate)
            self.error=self.y-yUpdate
            print(f"error: \n{self.error}")
            #print('Updated error is', self.error)
            self.weight=self.weight+ self.eta*np.dot(X_biased.T,self.error)
            print(f"updated weights after epoch: {i + 1}/{self.epochs}: \n{self.weight}")
            print(f"##"*10)
           #print('Updated weight is ', self.weight)
            
    def prediction(self,X_input):
        X_with_bias=np.c_[X_input,-np.ones((len(X_input),1))]
        z= self.weightUpdate(X_with_bias, self.weight)
        return self.activationFuction(z)
        

In [71]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
            
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
            

In [93]:
#prepare data for OR Gate
OR={"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,1,1,1]}
df_OR=pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [94]:
def prepare_data(df,target_col="y"):
    X=df.drop(target_col,axis=1)
    y=df[target_col]
    return X,y

In [95]:
X,y=prepare_data(df_OR)
X


x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [96]:
y


0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [76]:
ETA=0.1
EPOCHS=10
model_or=Perceptron(ETA,EPOCHS)


In [97]:
ETA=0.1
EPOCHS=10
model_or=perceptorn(ETA,EPOCHS)


In [98]:
model_or.fit(X, y)

--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[1 0 0 0]
error: 
0   -1
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.19987799  0.19984629 -0.20000281]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.19987799  0.19984629 -0.10000281]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 1.99877994e-01  1.99846288e-01 -2.81410313e-06]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 4/10: 
[0.19987799 0.19984

# AND GATE


In [105]:
AND={"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,0,0,1]}
df_AND=pd.DataFrame(AND)
df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [106]:
X,y=prepare_data(df_AND)

In [107]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [108]:
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [109]:
ETA=0.1
EPOCHS=10
model_AND=perceptorn(ETA,EPOCHS)

In [110]:
model_AND.fit(X,y)

--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-0.10003255 -0.10002791  0.29992441]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[-3.25464275e-05 -2.79056806e-05  1.99924411e-01]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[0.09996745 0.09997209 0.09992441]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 4/10: 
[-3.25464275e-05 -2.79

# XOR GATE

In [111]:
data={"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,1,1,0]}
df_XOR=pd.DataFrame(data);
df_XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [112]:
X,y=X,y=prepare_data(df_XOR)

In [113]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [114]:
y

0    0
1    1
2    1
3    0
Name: y, dtype: int64

In [118]:
ETA=0.1
EPOCHS=20
model_XOR=perceptorn(ETA,EPOCHS)

In [119]:
model_XOR.fit(X,y)

--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/20: 
[ 0.09985964  0.10005876 -0.19979166]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 2/20: 
[-1.40358483e-04  5.87566508e-05  2.08343619e-04]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 3/20: 
[ 0.09985964  0.10005876 -0.19979166]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 4/20: 
[-1.40358483e-04  5